//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockCharts.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quote
    {
        public System.DateTime Date { get; set; }
        public double Open { get; set; }
        public double High { get; set; }
        public double Low { get; set; }
        public double Close { get; set; }
        public long Volume { get; set; }
        public long SymbolId { get; set; }
        public long Id { get; set; }
    
        public virtual Symbol Symbol { get; set; }
    }
}
